config/routes.rb
Rails.application.routes.draw do
  resources :leagues

  devise_for :users
  root 'leagues#index'
  get "about" => "pages#about"
  get "new_league" => "pages#new_league"
  get "view_league" => "pages#view_league"
  get "friends" => "pages#friends"

end

app/models/league.rb
class League < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  def index
    @leagues = League.all.order "created_at DESC"
  end

  def show
  end
  
  def new
    @league = League.new
  end
  
  def edit
  end
 
  def create
    @league = League.new(league_params)
    if @league.save
        redirect_to @league, notice: 'League was successfully created.'
      else
        render action: 'new' 
      end
    end

  def update
      if @league.update(league_params)
        redirect_to @league, notice: 'League was successfully updated.'
      else
        render action: 'edit'
      end
    end

  def destroy
    @league.destroy
    redirect_to leagues_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:league_name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def About
  end

  def new_league
  end

  def view_league
  end

  def friends
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fantsey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :league_name %><br>
    <%= f.text_field :league_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :buy_In_Amount %><br>
    <%= f.text_field :buy_in_amount, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<% if user_signed_in? %>
<div class="jumbotron center">
  <h1>This is Fantasy Pay</h1>
<h3> Start a new league or check on a current one </h3>
<p></p>
<p></p>

<%= link_to "New League", new_league_path, class: "btn btn-primary btn-lg btn-block" %> 
<p></p>

<div id="box">
<table class="table">
  <thead>
    <tr>
      <th>League name</th>
      <th>Buy In Amount</th>
      <th>Number of players bought in</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= link_to league.league_name, league %></td>
        <td><%= league.buy_in_amount %></td>
        <td><%= '#' %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-edit"></span>'), edit_league_path(league) %></td>
        <td><%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'), league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br
</div>

<% else %>
<div class="jumbotron center">
  <h1>This is Fantasy Pay</h1>
  <h2>The easiest way to make sure all your friends buyin to your fantasy league. </h2> 
  <h3> Sign up or login to create a new leage.</h3>
  <p>
    <%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg" %> 
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>
  <% end %>

app/views/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p>
  <strong>League name:</strong>
  <%= @league.league_name %>
</p>
<p>
  <strong>Buy In Amount:</strong>
  <%= @league.buy_in_amount %>
</p>
<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>

app/views/pages/_home.html.erb
	<p>
		<%= link_to "New League", new_league_path, class: "btn btn-primary btn-lg btn-block" %> 
		<%#= link_to "View League", view_league_path, class: "btn btn-primary btn-lg btn-block" %>
	</p>
	<p> 
	</p>
	<p>
		<%#= link_to "Profile", edit_user_registration_path , class: "btn btn-default btn-lg btn-block" %> 
		<%#= link_to "Friends", friends_path, class: "btn btn-primary btn-lg btn-block" %>
	</p>
	<% else %>	
	<p>
		<%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg" %> 
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>
</div>

app/views/pages/about.html.erb
<h1>about us</h1>
<p> this page in under development </p>

app/views/pages/friends.html.erb
<h1> this is where you can see all your firends. not sure if this link is really needed right now however it is here for the time being. </h1>

app/views/pages/new_league.html.erb
<form>
  <div class="form-group">
    <label for="League_name">Leage Name</label>
    <input type="text" class="form-control" placeholder="League Name">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
</form>

<form class="form-group">
  <div class="form-group">
    <label for="exampleInputAmount">Player Buy In</label>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <input type="text" class="form-control" id="exampleInputAmount" placeholder="Amount">
      <div class="input-group-addon">.00</div>
    </div>
  </div>
  <button type="submit" class="btn btn-default">Add Contacts</button>
</form>
  <div>
  <button type="submit" class="btn btn-primary">Create and Invite</button>
</div>

app/views/pages/view_league.html.erb
<h1> This is where you can see all the leagues you are in and have been in </h1>